// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_add_1_to_age
List rcpp_add_1_to_age(List cows);
RcppExport SEXP _BLVIBMjp_rcpp_add_1_to_age(SEXP cowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cows(cowsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_add_1_to_age(cows));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_set_i_month
List rcpp_set_i_month(List cows, double i);
RcppExport SEXP _BLVIBMjp_rcpp_set_i_month(SEXP cowsSEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cows(cowsSEXP);
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_set_i_month(cows, i));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_extract_owned_cows
DataFrame rcpp_extract_owned_cows(DataFrame cows);
RcppExport SEXP _BLVIBMjp_rcpp_extract_owned_cows(SEXP cowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type cows(cowsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_extract_owned_cows(cows));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_construct_filepath
String rcpp_construct_filepath(std::string filename, Nullable<Rcpp::NumericVector> i, Nullable<Rcpp::String> subdir, std::string ext);
RcppExport SEXP _BLVIBMjp_rcpp_construct_filepath(SEXP filenameSEXP, SEXP iSEXP, SEXP subdirSEXP, SEXP extSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< Nullable<Rcpp::NumericVector> >::type i(iSEXP);
    Rcpp::traits::input_parameter< Nullable<Rcpp::String> >::type subdir(subdirSEXP);
    Rcpp::traits::input_parameter< std::string >::type ext(extSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_construct_filepath(filename, i, subdir, ext));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BLVIBMjp_rcpp_add_1_to_age", (DL_FUNC) &_BLVIBMjp_rcpp_add_1_to_age, 1},
    {"_BLVIBMjp_rcpp_set_i_month", (DL_FUNC) &_BLVIBMjp_rcpp_set_i_month, 2},
    {"_BLVIBMjp_rcpp_extract_owned_cows", (DL_FUNC) &_BLVIBMjp_rcpp_extract_owned_cows, 1},
    {"_BLVIBMjp_rcpp_construct_filepath", (DL_FUNC) &_BLVIBMjp_rcpp_construct_filepath, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_BLVIBMjp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
