# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Increment age column by 1
#'
#' @param cows cow data table
#' @export
rcpp_add_1_to_age <- function(cows) {
    .Call('_blvibmjp_rcpp_add_1_to_age', PACKAGE = 'blvibmjp', cows)
}

#' Add the month indicator
#'
#' @param cows cow data table
#' @param i numeric. The index of month.
#' @export
rcpp_set_i_month <- function(cows, i) {
    .Call('_blvibmjp_rcpp_set_i_month', PACKAGE = 'blvibmjp', cows, i)
}

#' Extract owned cows
#'
#' @param cows cow data frame
#' @export
rcpp_extract_owned_cows <- function(cows) {
    .Call('_blvibmjp_rcpp_extract_owned_cows', PACKAGE = 'blvibmjp', cows)
}

#' Construct filepath to output a file
#'
#' @param filename character. アウトプットファイル名.
#' @param i numeric. The file name will be like filename01.csv.
#' @param subdir character. A file is saved into data/output/subdir.
#' @param ext character. Extension of the output file.
#' @return character. data/output/subdir/filenameiext. eg. data/output/your_sub_directory/filename01.csv
#' @export
rcpp_construct_filepath <- function(filename, i = NULL, subdir = NULL, ext = ".csv") {
    .Call('_blvibmjp_rcpp_construct_filepath', PACKAGE = 'blvibmjp', filename, i, subdir, ext)
}

